# Generated by Django 3.2.6 on 2021-09-06 19:47

import app_event.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accounts', '0001_initial'),
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('category_name', models.CharField(max_length=50)),
                ('color_hex_code', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_user', to='app_accounts.usermodel')),
            ],
            bases=('app_base.basemodel',),
        ),
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timings', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_user', to='app_accounts.usermodel')),
            ],
            bases=('app_base.basemodel',),
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='file')),
                ('start', models.DateTimeField(blank=True, null=True, validators=[app_event.utils.date_time_valicator])),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('completed', 'Completed'), ('late', 'Done Late')], default='Pending', max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_event.categorymodel')),
                ('members', models.ManyToManyField(to='app_accounts.UserModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='app_accounts.usermodel')),
            ],
            bases=('app_base.basemodel',),
        ),
    ]
