# Generated by Django 3.2.6 on 2021-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='expiered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='status',
            field=models.CharField(choices=[('progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending'), ('late', 'Done Late')], default='In Progress', max_length=15),
        ),
    ]
