# Generated by Django 3.2.6 on 2021-09-06 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.baseuser')),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
            bases=('app_base.baseuser',),
        ),
    ]
